from typing import Protocol

from backend.db.models import Source


class SourceRepositoryProtocol(Protocol):
    def create_source(
        self,
        *,
        file_name: str,
        file_type: str,
        content: str,
        source_url: str | None = None,
    ) -> Source: ...

    def get_source(self, source_id: int) -> Source | None: ...

    def list_sources(self) -> list[Source]: ...


class ProductRepositoryProtocol(Protocol):
    def create_project(self, *, name: str, description: str): ...
    def get_project(self, project_id: int): ...
    def list_projects(self): ...
    def create_document(self, *, project_id: int, source_id: int, title: str): ...
    def list_documents_by_project(self, project_id: int): ...
    def get_source(self, source_id: int): ...
    def create_batch_run(self, *, project_id: int, mode: str, status: str = "completed"): ...
    def create_batch_item(self, *, batch_id: int, document_id: int, extracted_chars: int): ...
